// Code generated by "stringer -type PublicKeyType"; DO NOT EDIT

package main

import "fmt"

const _PublicKeyType_name = "PUTRSAPUTECDSAPUTED25519"

var _PublicKeyType_index = [...]uint8{0, 6, 14, 24}

func (i PublicKeyType) String() string {
	if i >= PublicKeyType(len(_PublicKeyType_index)-1) {
		return fmt.Sprintf("PublicKeyType(%d)", i)
	}
	return _PublicKeyType_name[_PublicKeyType_index[i]:_PublicKeyType_index[i+1]]
}
