// Code generated by "stringer -type ResourceType"; DO NOT EDIT

package main

import "fmt"

const _ResourceType_name = "RTPrivateKeyRTPublicKeyRTCSRRTCertificateRTLocationRTSerialRTSubject"

var _ResourceType_index = [...]uint8{0, 12, 23, 28, 41, 51, 59, 68}

func (i ResourceType) String() string {
	if i >= ResourceType(len(_ResourceType_index)-1) {
		return fmt.Sprintf("ResourceType(%d)", i)
	}
	return _ResourceType_name[_ResourceType_index[i]:_ResourceType_index[i+1]]
}
